### ISSUE TITLE
[ISSUE] Invalid persistentVolumes annotation indentation

### ISSUE THREAD

**Issue by moleman** [timescale/helm-charts#266]
**Describe the bug**
persistentVolumes.data.annotations is indented 8, should be 10

**To Reproduce**
Values:
```
persistentVolumes:
  data:
    annotations:
      test: test
```

**Output**
```
volumeClaimTemplates:
    - metadata:
        name: storage-volume
        annotations:
        test: test
```

**Expected behavior**
```
volumeClaimTemplates:
    - metadata:
        name: storage-volume
        annotations:
          test: test
```
