### ISSUE TITLE
HOw to allow non-ssl connections

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/helm-charts#284]
https://github.com/timescale/timescaledb-kubernetes/blob/46f40953bf617311e25d402314143c329148e7e2/charts/timescaledb-single/values.yaml#L228-L235

```
 pg_hba: 
 - local     all             postgres                     peer 
 - local     all             all                          md5 
 - host      all             all                all       scram-sha-256 
````

**Comment by 4nte** [comment]
I'm having the same issue. I'd like to disable SSL completely.

**Comment by steven-sheehy** [comment]
Here's how we did it:

```yaml
  patroni:
    bootstrap:
      dcs:
        postgresql:
          parameters:
            max_wal_size: 1GB
            max_worker_processes: 30  # Must be > max_background_workers + max_worker_processes (default 8)
            password_encryption: scram-sha-256
            shared_buffers: 2GB  # recommended to be 25% of available instance memory
            ssl: 'off'  # disable all ssl connections to not require Patroni certificate
            timescaledb.max_background_workers: 20
            work_mem: 50MB
    postgresql:
      pg_hba:
      - local     all             postgres                            peer           # allow local connections
      - local     all             all                                 scram-sha-256
      - hostnossl all,replication all               all               scram-sha-256  # allow TCP/IP connections (no ssl)
```

One thing to note is that the chart requires a RELEASE-NAME-certificate TLS secret regardless if you have TLS enabled or not. As a result we had to supply an empty tls certificate secret to make the chart happy. It would be nice if this volume was made optional.
