### ISSUE TITLE
Issue with schema validation

### ISSUE THREAD

**Issue by nhudson** [timescale/helm-charts#436]
**What happened?**

I believe with the release of `0.14.3` and this PR #434 that additional properties need to be added to the `values.schema.json` file to allow for the timescaledb-single helm chart to be used as a dependency chart like we do in tobs

**How to reproduce it (as minimally and precisely as possible)**:

Update the timescaledb-single Helm chart in tobs to `0.14.3` and run `helm template` on the chart.  You will get the following error

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
timescaledb-single:
- (root): Additional property enabled is not allowed
```

This is due to that we have this set in `Chart.yaml`

```
dependencies:
  - name: timescaledb-single
    condition: timescaledb-single.enabled
    version: 0.14.3
    repository: https://charts.timescale.com
```

We do not have validation for `enabled` in the schema.
