### ISSUE TITLE
Crash recovery fails when backup is disabled

### ISSUE THREAD

**Issue by agronholm** [timescale/helm-charts#442]
**What happened?**

Using the timescaledb-single chart, I deployed a stateful set of TimescaleDB with 2 replicas. Some time ago, the cluster was failing and I noticed this in the logs:

```
2022-08-29 09:15:54 UTC [33]: [630c81ea.21-397] @,app= [58P01] LOG:  could not stat file "pg_wal/RECOVERYXLOG": No such file or directory
2022-08-29 09:15:54 UTC [33]: [630c81ea.21-398] @,app= [58P01] DETAIL:  restore_command returned a zero exit status, but stat() failed.
2022-08-29 09:15:54 UTC [33]: [630c81ea.21-399] @,app= [58P01] LOG:  could not stat file "pg_wal/RECOVERYHISTORY": No such file or directory
2022-08-29 09:15:54 UTC [33]: [630c81ea.21-400] @,app= [58P01] DETAIL:  restore_command returned a zero exit status, but stat() failed.
```

Looking at the relevant script (`pgbackrest_archive_get.sh`), it seems it was always exiting with code 0 (success) since backups were not enabled, even when it did not produce the requested file. This is explicitly forbidden in the [PostgreSQL documentation](https://www.postgresql.org/docs/14/continuous-archiving.html):

```
It is important that the command return nonzero exit status on failure. The command will be called requesting files that are not present in the archive; it must return nonzero when so asked. This is not an error condition. An exception is that if the command was terminated by a signal (other than SIGTERM, which is used as part of a database server shutdown) or an error by the shell (such as command not found), then recovery will abort and the server will not start up.
```

**Did you expect to see something different?**

I expected the replica to recover after the crash.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure. Forcibly terminating a replica server might trigger this condition.

**Environment**

* Which helm chart and what version are you using?

timescaledb-single 0.10.0

* What is in your `values.yaml` ?

```yaml
  image:
    tag: pg14.1-ts2.5.1-latest
  replicaCount: 2
  clusterName: timescaledb
  loadBalancer:
    enabled: false
  persistence:
    size: 500Gi
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: dedicated
                operator: In
                values:
                  - pg-master
  tolerations:
    - key: dedicated
      operator: Equal
      value: pg-master
      effect: NoSchedule
  backup:
    enabled: false
    pgBackRest:
      repo1-s3-endpoint: eb-minio
      repo1-s3-bucket: backups
      repo1-s3-uri-style: path
      repo1-storage-verify-tls: "n"
      repo1-retention-full: 1
  prometheus:
    enabled: true
  patroni:
    bootstrap:
      dcs:
        postgresql:
          parameters:
            ssl: 'off'
    postgresql:
      create_replica_methods:
        - basebackup
      pg_hba:
        - local     all             postgres                              peer
        - local     all             all                                   md5
        - hostnossl all,replication all                all                md5
        - hostssl   all             all                127.0.0.1/32       md5
        - hostssl   all             all                ::1/128            md5
        - hostssl   replication     standby            all                md5
        - hostssl   all             all                all                md5
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"0ce33d4c6cd3c838648f245dba25f78a2a427fac", GitTreeState:"clean", BuildDate:"2022-06-17T15:23:06Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

    

* Kubernetes cluster kind:

  Azure AKS

**Anything else we need to know?**:
