### ISSUE TITLE
Specifying secret.pgbackrest does not override underlying pgbackrest properties

### ISSUE THREAD

**Issue by rituraj-AU** [timescale/helm-charts#507]
**What happened?**
This is what the final pgbackrest configmap render looks like:
```
data:
  pgbackrest.conf: |
    [global]
    compress-level=3
    compress-type=lz4
    process-max=4
    repo1-cipher-type=none
    repo1-path=/my/path/
    repo1-retention-diff=2
    repo1-retention-full=2
    repo1-s3-endpoint=s3.amazonaws.com
    repo1-s3-region=us-east-2  # This should be us-west-2
    repo1-type=s3
    spool-path=/var/run/postgresql
    start-fast=y
    [poddb]
    pg1-port=5432
    pg1-host-user=postgres
    pg1-path=/var/lib/postgresql/data
    pg1-socket-path=/var/run/postgresql
    link-all=y
    [global:archive-push]
    [global:archive-get]
```

**Did you expect to see something different?**
I expected the region to be `us-west-2`

**How to reproduce it (as minimally and precisely as possible)**:
See values below and deploy the chart

**Environment**
dev

* Which helm chart and what version are you using?
* 0.22.0

* What is in your `values.yaml` ?
```
timescaledb-single: 

  podAnnotations:
    iam.amazonaws.com/role: "arn:aws:iam::my.role"
    
  secrets:
    pgbackrest:
      PGBACKREST_REPO1_S3_REGION: "us-west-2"
      PGBACKREST_REPO1_S3_BUCKET: "arn-my-bucket"
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:23:02Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:18:00Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

  helm + concourse + argo

**Anything else we need to know?**:
Probably a pgbackrest issue, but specifying an IAM role with access to S3 bucket doesn't work as pgbackrest still forces me to specify a secret key and access key 🤷
