### ISSUE TITLE
RESTORE A SPECIFIC BACKUP WITH TIMESCALEDB HELM CHART

### ISSUE THREAD

**Issue by mahfoud-hub** [timescale/helm-charts#551]
HI can somebody help me to restore from a backup from a specific backup i can't find any configuration to add in the timescaledb values.yaml

**Comment by gunnarsundberg** [comment]
I was able to restore from a specific set in pgbackrest using the following in `values.yaml`:

```
secrets:
  pgbackrest:
    # Use the following to restore to a set other than latest.
    # Look at backups to determine set value. Will look something like 20230101-021203F_20230108-021203I
    PGBACKREST_SET: desired-set-name-here
```
