### ISSUE TITLE
timescale/timescaledb-single does not use `tls.crt` value in value.yaml

### ISSUE THREAD

**Issue by leoq-ardanlabs** [timescale/helm-charts#570]
Issue summary:

In `values.yaml`, I provide `tls.crt` and `tls.key` under certificate secrets (these values are from the example files in this repo):

```
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZCVENDQXUyZ0F3SUJBZ0lVWE9BR3
   xxxx ...
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpSQUlCQURBTkJna3Foa2lHOXcwQk
    xxxxx ...
  certificateSecretName: ""
```
But these provided values are not being used, helm continue to create self signed certs.

This is the command I run to get the secret:
```
kubectl get secret -n dev ugc-go-rest-service-stats-db-certificate -o json | jq -r '.data."tls.crt"'
```

Not sure if this is related, but this does seem to work when using `certificateSecretName`

```
certificate:
    tls.crt: ""
    tls.key: ""

  certificateSecretName: "ugc-go-rest-service-stats-db-tls" # Same values, but create the secrets ahead of time
```
