### ISSUE TITLE
Incompatibility introduced by v0.27

### ISSUE THREAD

**Issue by ignatiusreza** [timescale/helm-charts#576]
**What happened?**

The upgrade guide for [Upgrading to 0.27](https://github.com/timescale/helm-charts/blob/timescaledb-single-0.27.0/charts/timescaledb-single/docs/upgrade-guide.md#upgrading-to-027) mention

> This release removes `nameOverride` field from values.yaml in favor of `fullnameOverride`. If you were using `nameOverride` field, please update your values file to use the new field.

Which seems to indicate that no manual action need to be done for those who were not using `nameOverride`. But this is not the case, since the output of `"timescaledb.fullname"` change from `{{ Release.name }}-timescaledb` to `{{ Release.name }}`. Which makes the upgrade open to data lost, since new PVC will be scheduled to be created with the new name.

**Did you expect to see something different?**

The resolved `"timescaledb.fullname"` should not changed. This can be done by changing the default value for `fullnameOverride` from `{{ Release.name }}` to `{{ Release.name }}-timescaledb`.

Alternatively, update the "Upgrading to 0.27" guide to mention that `fullnameOverride: {{ Release.name }}-timescaledb` MUST be provided to allow seamless upgrade with no data lost.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy timescaledb-single of any version before 0.27
- Upgrade to 0.27

**Environment**

* Which helm chart and what version are you using?

* What is in your `values.yaml` ?

- before the upgrade (v0.13.1):

  ```
  timescaledb-single:
    enabled: true
    image:
      tag: pg14.2-ts2.6.1-latest
      repository: timescale/timescaledb-ha
    replicaCount: 1
    loadBalancer:
      enabled: false
    postInit:
      - secret:
          name: timescaledb-post-init
    secretNames:
      credentials: timescaledb-credentials
      certificate: timescaledb-certificate
  ```

- after the upgrade (v0.33.1):

  ```
  timescaledb-single:
    enabled: true
    image:
      tag: pg14.2-ts2.6.1-latest
      repository: timescale/timescaledb-ha
    replicaCount: 1
    postInit:
      - secret:
          name: timescaledb-post-init
    secrets:
      credentialsSecretName: timescaledb-credentials
  ```

* Kubernetes version information:

  `kubectl version`

    

* Kubernetes cluster kind:

  insert how you created your cluster: kops, bootkube, etc.

**Anything else we need to know?**:
