### ISSUE TITLE
pgbackrest conf does not reflect values in pgbackrestSecretName timescaledb-single

### ISSUE THREAD

**Issue by theelderbeever** [timescale/helm-charts#598]
**What happened?**
I populated a secret manually in our namespace to manage the pgbackrest settings and the S3 region was not reflected in the `pgbackrest.conf` file on the server resulting in the database not being able to find the bucket.

**Did you expect to see something different?**
I expected that when configuring a secret with the following values, specifically `PGBACKREST_REPO1_S3_REGION`, that the pgbackrest.conf would used them. It correctly uses the bucket strangely.

```
PGBACKREST_REPO1_S3_REGION
PGBACKREST_REPO1_S3_KEY
PGBACKREST_REPO1_S3_KEY_SECRET
PGBACKREST_REPO1_S3_BUCKET
PGBACKREST_REPO1_S3_ENDPOINT
```

**How to reproduce it (as minimally and precisely as possible)**:
Configure a secret manually using the following keys and set the `pgbackrestSecretName` to your created secret.

```
PGBACKREST_REPO1_S3_REGION: us-east-1
PGBACKREST_REPO1_S3_KEY: your-key
PGBACKREST_REPO1_S3_KEY_SECRET: your-secret
PGBACKREST_REPO1_S3_BUCKET: your-bucket
PGBACKREST_REPO1_S3_ENDPOINT: s3.amazonaws.com
```

**Environment**

* Which helm chart and what version are you using?
0.30.0

* What is in your `values.yaml` ?
```yaml
timescaledb-single:
  replicaCount: 2
  secrets:
    credentialsSecretName: "billing-platform-timescaledb-patroni"
    pgbackrestSecretName: "billing-platform-timescaledb-pgbackrest"

  backup:
    enabled: true
    
  service:
    primary:
      type: LoadBalancer
      port: 5432

    replica:
      type: LoadBalancer
      port: 5432

  persistentVolumes:
    data:
      enabled: true
      size: 250Gi
      storageClass: gp3-iops3k
    wal:
      enabled: true
      size: 25Gi
      storageClass: gp3-iops3k
  resources:
    limits:
      cpu: 2000m
      memory: 8192Mi
    requests:
      cpu: 2000m
      memory: 8192Mi

  sharedMemory:
    useMount: true

  pgBouncer:
    enabled: true
    port: 6432
    config:
      max_client_conn: 5000
      default_pool_size: 25

  prometheus:
    enabled: true
```

* Kubernetes version information:

  `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

AWS EKS via terraform code.

**Anything else we need to know?**:
