### ISSUE TITLE
Custom `readinessProbe` not possible through helm chart values

### ISSUE THREAD

**Issue by miguelv111** [timescale/helm-charts#602]
**What happened?**

I'm trying to deploy promscale on kubernetes with basic auth, using the official helm chart. To do so, I'm defining the following env vars: `PROMSCALE_WEB_AUTH_USERNAME` and `PROMSCALE_WEB_AUTH_PASSWORD`.

According with the [documentation](https://github.com/timescale/helm-charts/blob/main/charts/promscale/values.yaml#L123) we need to set a custom readinessProbe. Otherwise, using the default one we will get a 401 error and due to the readiness probe failure, the promscale service will be not accessible.

By applying the suggested custom readinessProbe, by setting `httpGet: null` an error arises: 

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
promscale:
- readinessProbe: httpGet is required
```
This way, is not possible to define a custom `readinessProbe` through helm chart values.

**Did you expect to see something different?**

It would be expected that by defining the `readinessProbe` as the documentation suggests, everything works fine.

```
readinessProbe:
  httpGet: null
  exec:
    command:
    - sh
    - -c
    - |-
      status_code=$(wget --server-response "http://${PROMSCALE_WEB_AUTH_USERNAME}:${PROMSCALE_WEB_AUTH_PASSWORD}@localhost:9201/healthz" 2>&1 | awk '/^  HTTP/{print $2}');
      if [[ "${status_code}" == "200" ]]; then exit 0; else exit 1; fi
```

**How to reproduce it (as minimally and precisely as possible)**:

By applying helm chart for promscale with the following values file:

```
extraEnv:
  - name: PROMSCALE_WEB_AUTH_USERNAME
    value: 'user'
  - name: PROMSCALE_WEB_AUTH_PASSWORD
    value: 'password'

readinessProbe:
  httpGet: null
  exec:
    command:
    - sh
    - -c
    - |-
      status_code=$(wget --server-response "http://${PROMSCALE_WEB_AUTH_USERNAME}:${PROMSCALE_WEB_AUTH_PASSWORD}@localhost:9201/healthz" 2>&1 | awk '/^  HTTP/{print $2}');
      if [[ "${status_code}" == "200" ]]; then exit 0; else exit 1; fi
```

**Environment**

* Which helm chart and what version are you using?

Helm chart: `timescale/promscale` from [https://charts.timescale.com/](https://charts.timescale.com/)

* What is in your `values.yaml` ?

```
extraEnv:
  - name: PROMSCALE_WEB_AUTH_USERNAME
    value: 'user'
  - name: PROMSCALE_WEB_AUTH_PASSWORD
    value: 'password'

readinessProbe:
  httpGet: null
  exec:
    command:
    - sh
    - -c
    - |-
      status_code=$(wget --server-response "http://${PROMSCALE_WEB_AUTH_USERNAME}:${PROMSCALE_WEB_AUTH_PASSWORD}@localhost:9201/healthz" 2>&1 | awk '/^  HTTP/{print $2}');
      if [[ "${status_code}" == "200" ]]; then exit 0; else exit 1; fi
```

* Kubernetes version information:

  Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.6

* Kubernetes cluster kind:

  insert how you created your cluster: kops, bootkube, etc.

**Anything else we need to know?**:
