### ISSUE TITLE
function counter_agg does not exist

### ISSUE THREAD

**Issue by Snazzie** [timescale/helm-charts#613]
**What did you do?**
Trying to execute a script that contains counter_agg function.
For some reason helm chart deployed pod does not have counter-agg function, even though the extension is enabled.

the same function works fine in my local docker instance
Both local docker instance and k8 pod have the same migration script applied.

**Did you expect to see some different?**

**Environment**

* Which helm chart and what version are you using?
timescaledb-single 0.33.1

* What is in your `values.yaml` ?
```yaml
timescaledb-single:
  image:
    tag: pg15
    pullPolicy: Always
  patroni:
    postgresql:
      parameters:
        checkpoint_completion_target: .9
  replicaCount: 1
  service:
    primary:
      annotations: 
        linkerd.io/inject: "false"

  podAnnotations: 
    linkerd.io/inject: "false"
  persistentVolumes:
    data:
      size: 10Gi
```

* Kubernetes version information:

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

 kurl.sh

**Anything else we need to know?**:

script
```sql
2023-06-24 23:03:06 UTC [145]: [649775cf.91-40] admin@metrics,app=[unknown] [42883] ERROR:  function counter_agg(timestamp with time zone, integer) does not exist at character 158

2023-06-24 23:03:06 UTC [145]: [649775cf.91-41] admin@metrics,app=[unknown] [42883] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

2023-06-24 23:03:06 UTC [145]: [649775cf.91-42] admin@metrics,app=[unknown] [42883] STATEMENT:

	SELECT c."TargetId" AS TargetId,

	time_bucket_gapfill('1 minutes', c."TimeStamp") AS time,

	avg("LatencyMs"),

	min("LatencyMs"),

	max("LatencyMs"),

	delta(

	    counter_agg("TimeStamp", "KeyspaceHits")

	),

	delta(

	    counter_agg("TimeStamp", "KeyspaceMisses")

	),

	avg("CpuUsagePercent"),

	min("CpuUsagePercent"),

	max("CpuUsagePercent"),

	avg("MemoryUsageKB"),

	min("MemoryUsageKB"),

	max("MemoryUsageKB"),

	locf(max("TotalSystemMemoryKB")),

	max("TotalKeys")

	FROM "HyperRedisMetrics" c

	WHERE c."TargetId" = 'fd3e558a-02af-4898-a54f-c15f351ea494' AND c."TimeStamp" >= '2023-06-24 22:03:03' AND c."TimeStamp" <= '2023-06-24 23:03:03'

	GROUP BY TargetId, time

	ORDER BY TargetId, time DESC
```
