### ISSUE TITLE
Operation not permitted on `/var/lib/postgresql/pgdata` while using with Amazon EFS

### ISSUE THREAD

**Issue by manoj016** [timescale/helm-charts#617]
**What did you do?**

I am using timescaledb-multinode  [helm charts](https://github.com/timescale/helm-charts/tree/main/charts/timescaledb-multinode)

I want to use Amazon EFS instead of local provisioner, so changed the `storageClass` inside the values.yaml file to `efs-cs`.

I am getting the below error in the initdb container for all the replicas.

```
install: cannot change owner and permissions of ‘/var/lib/postgresql/pgdata’: Operation not permitted
```

**Did you expect to see some different?**

The above is not working expected. The cluster should be up and running.

**Environment**

* Which helm chart and what version are you using?

[timescaledb-multinode](https://github.com/timescale/helm-charts/tree/main/charts/timescaledb-multinode)

timescaledb-image:  `timescale/timescaledb-ha:pg15.3-ts2.11.1-all`

* What is in your `values.yaml` ?
```
dataNodes: 3
nameOverride: timescaledb

image:
  repository: timescale/timescaledb-ha
  tag: pg15.3-ts2.11.1-all
  pullPolicy: IfNotPresent

credentials:
  accessNode:
    superuser: tea
  dataNode:
    superuser: coffee

env:
  - name: LC_ALL
    value: C.UTF-8
  - name: LANG
    value: C.UTF-8
  - name: PGDATA
    value: /var/lib/postgresql/pgdata

persistentVolume:
  enabled: true
  size: 200G
  storageClass: "efs-sc"
  subPath: ""
  mountPath: "/var/lib/postgresql"
  annotations:
    helm.sh/resource-policy: keep
    volume.beta.kubernetes.io/storage-class: efs-sc
  accessModes:
    - ReadWriteMany

resources: {}

postgresql:
  databases:
    - postgres
    - example
  parameters:
    max_connections: 100
    max_prepared_transactions: 150
    shared_buffers: 300MB
    work_mem: 16MB
    timescaledb.passfile: '../.pgpass'
    log_connections: 'on'
    log_line_prefix: "%t [%p]: [%c-%l] %u@%d,app=%a [%e] "
    log_min_duration_statement: '1s'
    log_statement: ddl
    log_checkpoints: 'on'
    log_lock_waits: 'on'
    min_wal_size: 256MB
    max_wal_size: 512MB
    temp_file_limit: 1GB

nodeSelector: {}
tolerations: []
affinityTemplate: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels:
            app:  {{ template "timescaledb.name" . }}
            release: {{ .Release.Name | quote }}
affinity: {}
rbac:
  create: true

serviceAccount:
  create: true
  name:
```

* Kubernetes version information:

  `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.5-eks-c12679a", GitCommit:"c03cecf98904742cce2e1183f87194102cc9dad9", GitTreeState:"clean", BuildDate:"2023-05-22T20:29:55Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
Amazon EKS
