### ISSUE TITLE
pgbackrest info missing stanza path when BOOTSTRAP_FROM_BACKUP=1

### ISSUE THREAD

**Issue by lazzarello** [timescale/helm-charts#628]
patroni fails to bootstrap from backup in restore_or_initdb method. This script cannot execute `pgbackrest info` when the environment variable BOOTSTRAP_FROM_BACKUP=1

I would like to bootstrap a new deployment from S3 backups, which are functioning correctly.

## Reproduction instructions

`helm upgrade --install --namespace troubleshooting -f values.yaml postgres-timescale-restore .`

values.yaml

```
image:
  repository: timescale/timescaledb-ha
  tag: pg14.6-ts2.9.3-patroni-dcs-failsafe-p0
  pullPolicy: IfNotPresent
persistentVolumes:
  data:
    size: 10Gi
    storageClass: ebs-sc
  wal:
    size: 10Gi
    storageClass: ebs-sc
nodeSelector:
  eks.amazonaws.com/nodegroup: timescaledb-20231023223903624400000001
patroni:
  bootstrap:
    dcs:
      postgresql:
        parameters:
          max_worker_processes: 64  # Must be > max_background_workers + max_worker_processes (default 8)
          max_parallel_workers: 32
          timescaledb.max_background_workers: 32
secrets:
  pgbackrest:
    PGBACKREST_REPO1_S3_REGION: "us-gov-west-1"
    PGBACKREST_REPO1_S3_KEY: "value"
    PGBACKREST_REPO1_S3_KEY_SECRET: "value"
    PGBACKREST_REPO1_S3_BUCKET: "timescaledb-wal-backups-dev"
    PGBACKREST_REPO1_S3_ENDPOINT: "s3.us-gov-west-1.amazonaws.com"
bootstrapFromBackup:
  enabled: True
  repo1-path: /default/postgres-timescale
backup:
  enabled: true
```

**Environment**

Chart is a fork of 0.33.1 with [this emptyDir PR merged](https://github.com/timescale/helm-charts/pull/578)

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-be83b3c", GitCommit:"d6adb24671245f68ce3cd985f6b68f124953968d", GitTreeState:"clean", BuildDate:"2023-09-27T17:22:23Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cluster type is EKS in AWS GovCloud created from Terraform. I'm working on a fix, so may have a PR ready in the coming week.
