### ISSUE TITLE
Chart requires all images to be installed form one repo, which does not allow for custom images

### ISSUE THREAD

**Issue by MarkCupitt** [timescale/helm-charts#642]
The chart has a common repo spec for all images in the pod

```
image:
  # Image was built from
  # https://github.com/timescale/timescaledb-docker-ha
  repository: timescale/timescaledb-ha
  #repository: markcupitt/timescaledb
  #tag: pg14.6-ts2.9.1-p1
  tag: {{timescaledb_image_version}}
  #tag: v1.0.0
  pullPolicy: IfNotPresent
```

This prevents the ability to load custom images in a bug fix or testing environment. IN addition, it enforces the same version for all containers which is not flexible or necessarily ideal

Adding image sections with repo, tag and pullPolicy for each container in the pod and the job would make this chart a lot more useful

image: (timescaledb)
timescaledbTune: 
pgBouncer:
prometheus: (already has own image spec)

timescaledb-patroni (job that tests config)
